In [1]:
class Course:
    def __init__(self, id, name, no_of_hours, no_of_valid_rooms, valid_rooms, max_no_hours_per_day, max_consecutive_hours, no_of_hours_to_schedule_when_assigning, class_flag, batch_flag):
        self.id = id
        self.name = name
        self.no_of_hours = no_of_hours
        self.no_of_valid_rooms= no_of_valid_rooms
        self.valid_rooms = valid_rooms
        self.max_no_hours_per_day = max_no_hours_per_day
        self.max_consecutive_hours = max_consecutive_hours
        self.no_of_hours_to_schedule_when_assigning = no_of_hours_to_schedule_when_assigning
        self.class_flag = class_flag
        self.batch_flag = batch_flag
        
class Student_Group:
    def __init__(self, id, name, courses):
        self.id = id
        self.name = name
        self.courses = courses

class Lecturer:
    def __init__(self, id, name, department, max_no_hours_per_day, max_no_hours_per_week, max_consecutive_hours, rank, availability, courses):
        self.id = id
        self.name = name
        self.department = department
        self.max_no_hours_per_day = max_no_hours_per_day
        self.max_no_hours_per_week = max_no_hours_per_week
        self.max_consecutive_hours = max_consecutive_hours
        self.rank = rank
        self.availability = availability
        self.courses = courses
        
class Room:
    def __init__(self, id, name):
        self.id = id
        self.name = name
class Day:
    def __init__(self, id, name):
        self.id = id
        self.name = name
class Hour:
    def __init__(self, id, name):
        self.id = id
        self.name = name

In [2]:
course_list = []
lecturer_list = []
student_group_list = []
rooms_list = []
days_list = []
hours_list = []
no_of_days = -1
no_of_hours = -1

with open("input.txt", "r") as f:
    lines = f.readlines()
    i = 0
    while(i<len(lines)):
        lines[i] = lines[i][:-1]
        print("i=",i)
        if lines[i] == "Days":
            i+=1
            no_of_days = int(lines[i][:-1])
            i+=1
            id = 0
            for j in range(i, i+no_of_days):
                name = lines[j][:-1]
                days_list.append(Day(id, name))
                id+=1
            i+=no_of_days
        elif lines[i] == "Hours":
            i+=1
            no_of_hours = int(lines[i][:-1])
            i+=1
            id = 0
            for j in range(i, i+no_of_hours):
                name = lines[j][:-1]
                hours_list.append(Hour(id, name))
                id+=1
            i+=no_of_hours
        elif lines[i] == "Courses":
            i+=1
            number_of_courses = int(lines[i][:-1])
            i+=1
            count = 0
            while(count<number_of_courses):
                course_id, course_name = lines[i][:-1].split(" ", 1)
                print(course_id, course_name)
                i+=1
                class_flag = bool(lines[i][:-1]=="True")
                i+=1
                batch_flag = bool(lines[i][:-1]=="True")
                i+=1
                no_of_hours_to_schedule_when_assigning = int(lines[i][:-1])
                i+=1
                max_no_hours_per_day = int(lines[i][:-1])
                i+=1
                no_hours_per_week = int(lines[i][:-1])
                i+=1
                max_consecutive_hours = int(lines[i][:-1])
                i+=1
                no_of_valid_rooms = int(lines[i][:-1])
                i+=1
                valid_rooms = []
                for j in range(i, i+no_of_valid_rooms):
                    valid_rooms.append(lines[j][:-1])
                i+=no_of_valid_rooms
                course_list.append(Course(course_id, course_name, no_hours_per_week, no_of_valid_rooms, valid_rooms, max_no_hours_per_day, max_consecutive_hours, no_of_hours_to_schedule_when_assigning, class_flag, batch_flag))
                count+=1
        elif lines[i] == "Rooms":
            i+=1
            number_of_rooms = int(lines[i][:-1])
            i+=1
            id = 0
            for j in range(i, i+number_of_rooms):
                name = lines[j][:-1]
                rooms_list.append(Room(id, name))
                id+=1
            i+=number_of_rooms
        elif lines[i] == "Student Groups":
            i+=1
            number_of_student_groups = int(lines[i][:-1])
            i+=1
            id = 0
            while(id<number_of_student_groups):
                name = lines[i][:-1]
                i+=1
                number_of_courses = int(lines[i][:-1])
                i+=1
                course_ids = []
                while(number_of_courses>0):
                    print(lines[i][:-1].split())
                    course = lines[i][:-1]
                    course_ids.append(course)
                    i+=1
                    number_of_courses-=1
                student_group_list.append(Student_Group(id, name, course_ids))
                id+=1
            
        elif lines[i] == "Lecturers":
            i+=1
            number_of_lecturers = int(lines[i][:-1])
            i+=1
            id = 0
            while(id<number_of_lecturers):
                name = lines[i][:-1]
                i+=1
                department = lines[i][:-1]
                i+=1
                max_no_hours_per_day = int(lines[i][:-1])
                i+=1
                max_no_hours_per_week = int(lines[i][:-1])
                i+=1
                max_consecutive_hours = int(lines[i][:-1])
                i+=1
                rank = lines[i][:-1]
                i+=1
                availability = [int(x) for x in lines[i][:-1].split()]
                i+=1
                no_of_courses = int(lines[i][:-1])
                i+=1
                course_ids = []
                while(no_of_courses>0):
                    print(lines[i][:-1])
                    course = lines[i][:-1]
                    course_ids.append(course)
                    i+=1
                    no_of_courses-=1
                lecturer_list.append(Lecturer(id, name, department, max_no_hours_per_day, max_no_hours_per_week, max_consecutive_hours, rank, availability, course_ids))
                id+=1
        else:
            i+=1

i= 0
i= 7
i= 8
i= 17
i= 18
i= 33
i= 34
CSC301 AM
CSC302 DLDA
CSC303 DM
CSC304 ECCF
CSC305 DS
CSL301 DSL
CSL302 BEL
CSL303 DataSL
CSL304 OOPM
CSC501 MP
CSC502 DBMS
CSC503 CN
CSC504 TCS
CSC505 BCE
CSDLO5013 AA
CSL501 MPL
CSL502 CNL
CSL503 DBMSL
CSL504 WDL
CSL505 BCEL
CSC701 DSIP
CSC702 MCC
CSC703 AISC
CSDL70X Dept Level Elective
ILO70XX Inst Level Elective
CSL701 DSIPL
CSL702 MADTL
CSL703 AISCL
CSL704 CL
CSP705 Major Project
i= 306
i= 307
['CSC301']
['CSC302']
['CSC303']
['CSC304']
['CSC305']
['CSL301']
['CSL302']
['CSL303']
['CSL304']
['CSC501']
['CSC502']
['CSC503']
['CSC504']
['CSC505']
['CSDLO5013']
['CSL501']
['CSL502']
['CSL503']
['CSL504']
['CSL505']
['CSC701']
['CSC702']
['CSC703']
['CSDL70X']
['ILO70XX']
['CSL701']
['CSL702']
['CSL703']
['CSL704']
['CSP705']
i= 345
i= 346
CSC301
CSC302
CSL301
CSC303
CSC502
CSC304
CSL302
CSC305
CSL303
CSC501
CSC505
CSC503
CSC504
CSC702
CSL304
CSL504
CSC701
CSL505
CSL701
CSC703
CSDLO5013
CSDL70X
ILO70XX
CSL502
CSL703
CSL503
CSL702
CSL704
CSL501

In [3]:
course_list[0].valid_rooms

['CR2']

In [4]:
day_dictionary = {}
for day in days_list:
    day_dictionary[day.id] = day
    
hour_dictionary = {}
for hour in hours_list:
    hour_dictionary[hour.id] = hour
    
lecturer_dictionary = {}
for lecturer in lecturer_list:
    lecturer_dictionary[lecturer.id] = lecturer
    
student_group_dictionary = {}
for student_group in student_group_list:
    student_group_dictionary[student_group.id] = student_group
    
course_dictionary = {}
for course in course_list:
    course_dictionary[course.id] = course

In [7]:
columns = {}
hours_for_columns = {}
count = 0
for sg in student_group_list:
    for course_sg in sg.courses:
        for lecturer in lecturer_list:
            for course_l in lecturer.courses:
                if course_sg == course_l and course_dictionary[course_sg].class_flag:
                    columns[count] = {"lecturer":lecturer.id, "student_group":sg.id, "course": course_l, "subset":"all"}
                    hours_for_columns[count] = course_dictionary[course_sg].no_of_hours
                    count+=1
                if course_sg == course_l and course_dictionary[course_sg].batch_flag:
                    for num in range(4):
                        columns[count] = {"lecturer":lecturer.id, "student_group":sg.id, "course": course_l, "subset":"batch", "batch":num}
                        hours_for_columns[count] = course_dictionary[course_sg].no_of_hours
                        count+=1

In [6]:
columns = {}
hours_for_columns = {}
count = 0
sg = student_group_list[0]
for course_sg in sg.courses:
    for lecturer in lecturer_list:
        for course_l in lecturer.courses:
            if course_sg == course_l and course_dictionary[course_sg].class_flag:
                columns[count] = {"lecturer":lecturer.id, "student_group":sg.id, "course": course_l, "subset":"all"}
                hours_for_columns[count] = course_dictionary[course_sg].no_of_hours
                count+=1
            if course_sg == course_l and course_dictionary[course_sg].batch_flag:
                for num in range(4):
                    columns[count] = {"lecturer":lecturer.id, "student_group":sg.id, "course": course_l, "subset":"batch", "batch":num}
                    hours_for_columns[count] = course_dictionary[course_sg].no_of_hours
                    count+=1

In [8]:
columns

{0: {'lecturer': 0, 'student_group': 0, 'course': 'CSC301', 'subset': 'all'},
 1: {'lecturer': 1, 'student_group': 0, 'course': 'CSC302', 'subset': 'all'},
 2: {'lecturer': 2, 'student_group': 0, 'course': 'CSC303', 'subset': 'all'},
 3: {'lecturer': 3, 'student_group': 0, 'course': 'CSC304', 'subset': 'all'},
 4: {'lecturer': 4, 'student_group': 0, 'course': 'CSC305', 'subset': 'all'},
 5: {'lecturer': 1,
  'student_group': 0,
  'course': 'CSL301',
  'subset': 'batch',
  'batch': 0},
 6: {'lecturer': 1,
  'student_group': 0,
  'course': 'CSL301',
  'subset': 'batch',
  'batch': 1},
 7: {'lecturer': 1,
  'student_group': 0,
  'course': 'CSL301',
  'subset': 'batch',
  'batch': 2},
 8: {'lecturer': 1,
  'student_group': 0,
  'course': 'CSL301',
  'subset': 'batch',
  'batch': 3},
 9: {'lecturer': 3,
  'student_group': 0,
  'course': 'CSL302',
  'subset': 'batch',
  'batch': 0},
 10: {'lecturer': 3,
  'student_group': 0,
  'course': 'CSL302',
  'subset': 'batch',
  'batch': 1},
 11: {'lecturer': 3,
  'student_group': 0,
  'course': 'CSL302',
  'subset': 'batch',
  'batch': 2},
 12: {'lecturer': 3,
  'student_group': 0,
  'course': 'CSL302',
  'subset': 'batch',
  'batch': 3},
 13: {'lecturer': 4,
  'student_group': 0,
  'course': 'CSL303',
  'subset': 'batch',
  'batch': 0},
 14: {'lecturer': 4,
  'student_group': 0,
  'course': 'CSL303',
  'subset': 'batch',
  'batch': 1},
 15: {'lecturer': 4,
  'student_group': 0,
  'course': 'CSL303',
  'subset': 'batch',
  'batch': 2},
 16: {'lecturer': 4,
  'student_group': 0,
  'course': 'CSL303',
  'subset': 'batch',
  'batch': 3},
 17: {'lecturer': 7,
  'student_group': 0,
  'course': 'CSL304',
  'subset': 'batch',
  'batch': 0},
 18: {'lecturer': 7,
  'student_group': 0,
  'course': 'CSL304',
  'subset': 'batch',
  'batch': 1},
 19: {'lecturer': 7,
  'student_group': 0,
  'course': 'CSL304',
  'subset': 'batch',
  'batch': 2},
 20: {'lecturer': 7,
  'student_group': 0,
  'course': 'CSL304',
  'subset': 'batch',
  'batch': 3},
 21: {'lecturer': 5, 'student_group': 1, 'course': 'CSC501', 'subset': 'all'},
 22: {'lecturer': 2, 'student_group': 1, 'course': 'CSC502', 'subset': 'all'},
 23: {'lecturer': 6, 'student_group': 1, 'course': 'CSC503', 'subset': 'all'},
 24: {'lecturer': 6, 'student_group': 1, 'course': 'CSC504', 'subset': 'all'},
 25: {'lecturer': 5, 'student_group': 1, 'course': 'CSC505', 'subset': 'all'},
 26: {'lecturer': 9,
  'student_group': 1,
  'course': 'CSDLO5013',
  'subset': 'all'},
 27: {'lecturer': 13,
  'student_group': 1,
  'course': 'CSL501',
  'subset': 'batch',
  'batch': 0},
 28: {'lecturer': 13,
  'student_group': 1,
  'course': 'CSL501',
  'subset': 'batch',
  'batch': 1},
 29: {'lecturer': 13,
  'student_group': 1,
  'course': 'CSL501',
  'subset': 'batch',
  'batch': 2},
 30: {'lecturer': 13,
  'student_group': 1,
  'course': 'CSL501',
  'subset': 'batch',
  'batch': 3},
 31: {'lecturer': 11,
  'student_group': 1,
  'course': 'CSL502',
  'subset': 'batch',
  'batch': 0},
 32: {'lecturer': 11,
  'student_group': 1,
  'course': 'CSL502',
  'subset': 'batch',
  'batch': 1},
 33: {'lecturer': 11,
  'student_group': 1,
  'course': 'CSL502',
  'subset': 'batch',
  'batch': 2},
 34: {'lecturer': 11,
  'student_group': 1,
  'course': 'CSL502',
  'subset': 'batch',
  'batch': 3},
 35: {'lecturer': 12,
  'student_group': 1,
  'course': 'CSL503',
  'subset': 'batch',
  'batch': 0},
 36: {'lecturer': 12,
  'student_group': 1,
  'course': 'CSL503',
  'subset': 'batch',
  'batch': 1},
 37: {'lecturer': 12,
  'student_group': 1,
  'course': 'CSL503',
  'subset': 'batch',
  'batch': 2},
 38: {'lecturer': 12,
  'student_group': 1,
  'course': 'CSL503',
  'subset': 'batch',
  'batch': 3},
 39: {'lecturer': 7,
  'student_group': 1,
  'course': 'CSL504',
  'subset': 'batch',
  'batch': 0},
 40: {'lecturer': 7,
  'student_group': 1,
  'course': 'CSL504',
  'subset': 'batch',
  'batch': 1},
 41: {'lecturer': 7,
  'student_group': 1,
  'course': 'CSL504',
  'subset': 'batch',
  'batch': 2},
 42: {'lecturer': 7,
  'student_group': 1,
  'course': 'CSL504',
  'subset': 'batch',
  'batch': 3},
 43: {'lecturer': 8,
  'student_group': 1,
  'course': 'CSL505',
  'subset': 'batch',
  'batch': 0},
 44: {'lecturer': 8,
  'student_group': 1,
  'course': 'CSL505',
  'subset': 'batch',
  'batch': 1},
 45: {'lecturer': 8,
  'student_group': 1,
  'course': 'CSL505',
  'subset': 'batch',
  'batch': 2},
 46: {'lecturer': 8,
  'student_group': 1,
  'course': 'CSL505',
  'subset': 'batch',
  'batch': 3},
 47: {'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'},
 48: {'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'},
 49: {'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'},
 50: {'lecturer': 10,
  'student_group': 2,
  'course': 'CSDL70X',
  'subset': 'all'},
 51: {'lecturer': 10,
  'student_group': 2,
  'course': 'ILO70XX',
  'subset': 'all'},
 52: {'lecturer': 8,
  'student_group': 2,
  'course': 'CSL701',
  'subset': 'batch',
  'batch': 0},
 53: {'lecturer': 8,
  'student_group': 2,
  'course': 'CSL701',
  'subset': 'batch',
  'batch': 1},
 54: {'lecturer': 8,
  'student_group': 2,
  'course': 'CSL701',
  'subset': 'batch',
  'batch': 2},
 55: {'lecturer': 8,
  'student_group': 2,
  'course': 'CSL701',
  'subset': 'batch',
  'batch': 3},
 56: {'lecturer': 12,
  'student_group': 2,
  'course': 'CSL702',
  'subset': 'batch',
  'batch': 0},
 57: {'lecturer': 12,
  'student_group': 2,
  'course': 'CSL702',
  'subset': 'batch',
  'batch': 1},
 58: {'lecturer': 12,
  'student_group': 2,
  'course': 'CSL702',
  'subset': 'batch',
  'batch': 2},
 59: {'lecturer': 12,
  'student_group': 2,
  'course': 'CSL702',
  'subset': 'batch',
  'batch': 3},
 60: {'lecturer': 11,
  'student_group': 2,
  'course': 'CSL703',
  'subset': 'batch',
  'batch': 0},
 61: {'lecturer': 11,
  'student_group': 2,
  'course': 'CSL703',
  'subset': 'batch',
  'batch': 1},
 62: {'lecturer': 11,
  'student_group': 2,
  'course': 'CSL703',
  'subset': 'batch',
  'batch': 2},
 63: {'lecturer': 11,
  'student_group': 2,
  'course': 'CSL703',
  'subset': 'batch',
  'batch': 3},
 64: {'lecturer': 13,
  'student_group': 2,
  'course': 'CSL704',
  'subset': 'batch',
  'batch': 0},
 65: {'lecturer': 13,
  'student_group': 2,
  'course': 'CSL704',
  'subset': 'batch',
  'batch': 1},
 66: {'lecturer': 13,
  'student_group': 2,
  'course': 'CSL704',
  'subset': 'batch',
  'batch': 2},
 67: {'lecturer': 13,
  'student_group': 2,
  'course': 'CSL704',
  'subset': 'batch',
  'batch': 3}}

In [9]:
hours_for_columns

{0: 5,
 1: 4,
 2: 4,
 3: 4,
 4: 4,
 5: 2,
 6: 2,
 7: 2,
 8: 2,
 9: 2,
 10: 2,
 11: 2,
 12: 2,
 13: 2,
 14: 2,
 15: 2,
 16: 2,
 17: 2,
 18: 2,
 19: 2,
 20: 2,
 21: 4,
 22: 4,
 23: 4,
 24: 4,
 25: 2,
 26: 4,
 27: 2,
 28: 2,
 29: 2,
 30: 2,
 31: 2,
 32: 2,
 33: 2,
 34: 2,
 35: 2,
 36: 2,
 37: 2,
 38: 2,
 39: 2,
 40: 2,
 41: 2,
 42: 2,
 43: 2,
 44: 2,
 45: 2,
 46: 2,
 47: 4,
 48: 4,
 49: 4,
 50: 4,
 51: 3,
 52: 2,
 53: 2,
 54: 2,
 55: 2,
 56: 2,
 57: 2,
 58: 2,
 59: 2,
 60: 2,
 61: 2,
 62: 2,
 63: 2,
 64: 2,
 65: 2,
 66: 2,
 67: 2}

In [10]:
total_hours = 0
for hours in hours_for_columns:
    total_hours+=hours_for_columns[hours]

In [11]:
total_hours

166

In [12]:
column_numbers = [x for x in range(0, len(columns))]

In [13]:
column_numbers

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67]

In [14]:
import random

In [15]:
intial_population = []
for x in range(20):
    q=column_numbers.copy()
    random.shuffle(q)
    intial_population.append(q)

In [16]:
len(intial_population)

20

In [17]:
random.shuffle(column_numbers)

In [18]:
column_numbers

[24,
 38,
 10,
 30,
 63,
 16,
 12,
 54,
 59,
 48,
 17,
 65,
 29,
 14,
 5,
 35,
 18,
 37,
 13,
 50,
 64,
 55,
 0,
 25,
 19,
 32,
 4,
 11,
 33,
 31,
 39,
 42,
 22,
 9,
 60,
 34,
 40,
 44,
 43,
 57,
 2,
 27,
 21,
 46,
 47,
 49,
 1,
 53,
 26,
 28,
 52,
 51,
 66,
 67,
 61,
 56,
 20,
 62,
 45,
 6,
 36,
 8,
 41,
 58,
 15,
 23,
 3,
 7]

In [19]:
rows = {}
count = 0
for room in rooms_list:
    for day in days_list:
        for hour in hours_list:
            rows[count] = {"day": day.id, "hour": hour.id, "room": room.id}
            count+=1

In [20]:
rows

{0: {'day': 0, 'hour': 0, 'room': 0},
 1: {'day': 0, 'hour': 1, 'room': 0},
 2: {'day': 0, 'hour': 2, 'room': 0},
 3: {'day': 0, 'hour': 3, 'room': 0},
 4: {'day': 0, 'hour': 4, 'room': 0},
 5: {'day': 0, 'hour': 5, 'room': 0},
 6: {'day': 0, 'hour': 6, 'room': 0},
 7: {'day': 1, 'hour': 0, 'room': 0},
 8: {'day': 1, 'hour': 1, 'room': 0},
 9: {'day': 1, 'hour': 2, 'room': 0},
 10: {'day': 1, 'hour': 3, 'room': 0},
 11: {'day': 1, 'hour': 4, 'room': 0},
 12: {'day': 1, 'hour': 5, 'room': 0},
 13: {'day': 1, 'hour': 6, 'room': 0},
 14: {'day': 2, 'hour': 0, 'room': 0},
 15: {'day': 2, 'hour': 1, 'room': 0},
 16: {'day': 2, 'hour': 2, 'room': 0},
 17: {'day': 2, 'hour': 3, 'room': 0},
 18: {'day': 2, 'hour': 4, 'room': 0},
 19: {'day': 2, 'hour': 5, 'room': 0},
 20: {'day': 2, 'hour': 6, 'room': 0},
 21: {'day': 3, 'hour': 0, 'room': 0},
 22: {'day': 3, 'hour': 1, 'room': 0},
 23: {'day': 3, 'hour': 2, 'room': 0},
 24: {'day': 3, 'hour': 3, 'room': 0},
 25: {'day': 3, 'hour': 4, 'room': 0},
 26: {'day': 3, 'hour': 5, 'room': 0},
 27: {'day': 3, 'hour': 6, 'room': 0},
 28: {'day': 4, 'hour': 0, 'room': 0},
 29: {'day': 4, 'hour': 1, 'room': 0},
 30: {'day': 4, 'hour': 2, 'room': 0},
 31: {'day': 4, 'hour': 3, 'room': 0},
 32: {'day': 4, 'hour': 4, 'room': 0},
 33: {'day': 4, 'hour': 5, 'room': 0},
 34: {'day': 4, 'hour': 6, 'room': 0},
 35: {'day': 0, 'hour': 0, 'room': 1},
 36: {'day': 0, 'hour': 1, 'room': 1},
 37: {'day': 0, 'hour': 2, 'room': 1},
 38: {'day': 0, 'hour': 3, 'room': 1},
 39: {'day': 0, 'hour': 4, 'room': 1},
 40: {'day': 0, 'hour': 5, 'room': 1},
 41: {'day': 0, 'hour': 6, 'room': 1},
 42: {'day': 1, 'hour': 0, 'room': 1},
 43: {'day': 1, 'hour': 1, 'room': 1},
 44: {'day': 1, 'hour': 2, 'room': 1},
 45: {'day': 1, 'hour': 3, 'room': 1},
 46: {'day': 1, 'hour': 4, 'room': 1},
 47: {'day': 1, 'hour': 5, 'room': 1},
 48: {'day': 1, 'hour': 6, 'room': 1},
 49: {'day': 2, 'hour': 0, 'room': 1},
 50: {'day': 2, 'hour': 1, 'room': 1},
 51: {'day': 2, 'hour': 2, 'room': 1},
 52: {'day': 2, 'hour': 3, 'room': 1},
 53: {'day': 2, 'hour': 4, 'room': 1},
 54: {'day': 2, 'hour': 5, 'room': 1},
 55: {'day': 2, 'hour': 6, 'room': 1},
 56: {'day': 3, 'hour': 0, 'room': 1},
 57: {'day': 3, 'hour': 1, 'room': 1},
 58: {'day': 3, 'hour': 2, 'room': 1},
 59: {'day': 3, 'hour': 3, 'room': 1},
 60: {'day': 3, 'hour': 4, 'room': 1},
 61: {'day': 3, 'hour': 5, 'room': 1},
 62: {'day': 3, 'hour': 6, 'room': 1},
 63: {'day': 4, 'hour': 0, 'room': 1},
 64: {'day': 4, 'hour': 1, 'room': 1},
 65: {'day': 4, 'hour': 2, 'room': 1},
 66: {'day': 4, 'hour': 3, 'room': 1},
 67: {'day': 4, 'hour': 4, 'room': 1},
 68: {'day': 4, 'hour': 5, 'room': 1},
 69: {'day': 4, 'hour': 6, 'room': 1},
 70: {'day': 0, 'hour': 0, 'room': 2},
 71: {'day': 0, 'hour': 1, 'room': 2},
 72: {'day': 0, 'hour': 2, 'room': 2},
 73: {'day': 0, 'hour': 3, 'room': 2},
 74: {'day': 0, 'hour': 4, 'room': 2},
 75: {'day': 0, 'hour': 5, 'room': 2},
 76: {'day': 0, 'hour': 6, 'room': 2},
 77: {'day': 1, 'hour': 0, 'room': 2},
 78: {'day': 1, 'hour': 1, 'room': 2},
 79: {'day': 1, 'hour': 2, 'room': 2},
 80: {'day': 1, 'hour': 3, 'room': 2},
 81: {'day': 1, 'hour': 4, 'room': 2},
 82: {'day': 1, 'hour': 5, 'room': 2},
 83: {'day': 1, 'hour': 6, 'room': 2},
 84: {'day': 2, 'hour': 0, 'room': 2},
 85: {'day': 2, 'hour': 1, 'room': 2},
 86: {'day': 2, 'hour': 2, 'room': 2},
 87: {'day': 2, 'hour': 3, 'room': 2},
 88: {'day': 2, 'hour': 4, 'room': 2},
 89: {'day': 2, 'hour': 5, 'room': 2},
 90: {'day': 2, 'hour': 6, 'room': 2},
 91: {'day': 3, 'hour': 0, 'room': 2},
 92: {'day': 3, 'hour': 1, 'room': 2},
 93: {'day': 3, 'hour': 2, 'room': 2},
 94: {'day': 3, 'hour': 3, 'room': 2},
 95: {'day': 3, 'hour': 4, 'room': 2},
 96: {'day': 3, 'hour': 5, 'room': 2},
 97: {'day': 3, 'hour': 6, 'room': 2},
 98: {'day': 4, 'hour': 0, 'room': 2},
 99: {'day': 4, 'hour': 1, 'room': 2},
 100: {'day': 4, 'hour': 2, 'room': 2},
 101: {'day': 4, 'hour': 3, 'room': 2},
 102: {'day': 4, 'hour': 4, 'room': 2},
 103: {'day': 4, 'hour': 5, 'room': 2},
 104: {'day': 4, 'hour': 6, 'room': 2},
 105: {'day': 0, 'hour': 0, 'room': 3},
 106: {'day': 0, 'hour': 1, 'room': 3},
 107: {'day': 0, 'hour': 2, 'room': 3},
 108: {'day': 0, 'hour': 3, 'room': 3},
 109: {'day': 0, 'hour': 4, 'room': 3},
 110: {'day': 0, 'hour': 5, 'room': 3},
 111: {'day': 0, 'hour': 6, 'room': 3},
 112: {'day': 1, 'hour': 0, 'room': 3},
 113: {'day': 1, 'hour': 1, 'room': 3},
 114: {'day': 1, 'hour': 2, 'room': 3},
 115: {'day': 1, 'hour': 3, 'room': 3},
 116: {'day': 1, 'hour': 4, 'room': 3},
 117: {'day': 1, 'hour': 5, 'room': 3},
 118: {'day': 1, 'hour': 6, 'room': 3},
 119: {'day': 2, 'hour': 0, 'room': 3},
 120: {'day': 2, 'hour': 1, 'room': 3},
 121: {'day': 2, 'hour': 2, 'room': 3},
 122: {'day': 2, 'hour': 3, 'room': 3},
 123: {'day': 2, 'hour': 4, 'room': 3},
 124: {'day': 2, 'hour': 5, 'room': 3},
 125: {'day': 2, 'hour': 6, 'room': 3},
 126: {'day': 3, 'hour': 0, 'room': 3},
 127: {'day': 3, 'hour': 1, 'room': 3},
 128: {'day': 3, 'hour': 2, 'room': 3},
 129: {'day': 3, 'hour': 3, 'room': 3},
 130: {'day': 3, 'hour': 4, 'room': 3},
 131: {'day': 3, 'hour': 5, 'room': 3},
 132: {'day': 3, 'hour': 6, 'room': 3},
 133: {'day': 4, 'hour': 0, 'room': 3},
 134: {'day': 4, 'hour': 1, 'room': 3},
 135: {'day': 4, 'hour': 2, 'room': 3},
 136: {'day': 4, 'hour': 3, 'room': 3},
 137: {'day': 4, 'hour': 4, 'room': 3},
 138: {'day': 4, 'hour': 5, 'room': 3},
 139: {'day': 4, 'hour': 6, 'room': 3},
 140: {'day': 0, 'hour': 0, 'room': 4},
 141: {'day': 0, 'hour': 1, 'room': 4},
 142: {'day': 0, 'hour': 2, 'room': 4},
 143: {'day': 0, 'hour': 3, 'room': 4},
 144: {'day': 0, 'hour': 4, 'room': 4},
 145: {'day': 0, 'hour': 5, 'room': 4},
 146: {'day': 0, 'hour': 6, 'room': 4},
 147: {'day': 1, 'hour': 0, 'room': 4},
 148: {'day': 1, 'hour': 1, 'room': 4},
 149: {'day': 1, 'hour': 2, 'room': 4},
 150: {'day': 1, 'hour': 3, 'room': 4},
 151: {'day': 1, 'hour': 4, 'room': 4},
 152: {'day': 1, 'hour': 5, 'room': 4},
 153: {'day': 1, 'hour': 6, 'room': 4},
 154: {'day': 2, 'hour': 0, 'room': 4},
 155: {'day': 2, 'hour': 1, 'room': 4},
 156: {'day': 2, 'hour': 2, 'room': 4},
 157: {'day': 2, 'hour': 3, 'room': 4},
 158: {'day': 2, 'hour': 4, 'room': 4},
 159: {'day': 2, 'hour': 5, 'room': 4},
 160: {'day': 2, 'hour': 6, 'room': 4},
 161: {'day': 3, 'hour': 0, 'room': 4},
 162: {'day': 3, 'hour': 1, 'room': 4},
 163: {'day': 3, 'hour': 2, 'room': 4},
 164: {'day': 3, 'hour': 3, 'room': 4},
 165: {'day': 3, 'hour': 4, 'room': 4},
 166: {'day': 3, 'hour': 5, 'room': 4},
 167: {'day': 3, 'hour': 6, 'room': 4},
 168: {'day': 4, 'hour': 0, 'room': 4},
 169: {'day': 4, 'hour': 1, 'room': 4},
 170: {'day': 4, 'hour': 2, 'room': 4},
 171: {'day': 4, 'hour': 3, 'room': 4},
 172: {'day': 4, 'hour': 4, 'room': 4},
 173: {'day': 4, 'hour': 5, 'room': 4},
 174: {'day': 4, 'hour': 6, 'room': 4},
 175: {'day': 0, 'hour': 0, 'room': 5},
 176: {'day': 0, 'hour': 1, 'room': 5},
 177: {'day': 0, 'hour': 2, 'room': 5},
 178: {'day': 0, 'hour': 3, 'room': 5},
 179: {'day': 0, 'hour': 4, 'room': 5},
 180: {'day': 0, 'hour': 5, 'room': 5},
 181: {'day': 0, 'hour': 6, 'room': 5},
 182: {'day': 1, 'hour': 0, 'room': 5},
 183: {'day': 1, 'hour': 1, 'room': 5},
 184: {'day': 1, 'hour': 2, 'room': 5},
 185: {'day': 1, 'hour': 3, 'room': 5},
 186: {'day': 1, 'hour': 4, 'room': 5},
 187: {'day': 1, 'hour': 5, 'room': 5},
 188: {'day': 1, 'hour': 6, 'room': 5},
 189: {'day': 2, 'hour': 0, 'room': 5},
 190: {'day': 2, 'hour': 1, 'room': 5},
 191: {'day': 2, 'hour': 2, 'room': 5},
 192: {'day': 2, 'hour': 3, 'room': 5},
 193: {'day': 2, 'hour': 4, 'room': 5},
 194: {'day': 2, 'hour': 5, 'room': 5},
 195: {'day': 2, 'hour': 6, 'room': 5},
 196: {'day': 3, 'hour': 0, 'room': 5},
 197: {'day': 3, 'hour': 1, 'room': 5},
 198: {'day': 3, 'hour': 2, 'room': 5},
 199: {'day': 3, 'hour': 3, 'room': 5},
 200: {'day': 3, 'hour': 4, 'room': 5},
 201: {'day': 3, 'hour': 5, 'room': 5},
 202: {'day': 3, 'hour': 6, 'room': 5},
 203: {'day': 4, 'hour': 0, 'room': 5},
 204: {'day': 4, 'hour': 1, 'room': 5},
 205: {'day': 4, 'hour': 2, 'room': 5},
 206: {'day': 4, 'hour': 3, 'room': 5},
 207: {'day': 4, 'hour': 4, 'room': 5},
 208: {'day': 4, 'hour': 5, 'room': 5},
 209: {'day': 4, 'hour': 6, 'room': 5},
 210: {'day': 0, 'hour': 0, 'room': 6},
 211: {'day': 0, 'hour': 1, 'room': 6},
 212: {'day': 0, 'hour': 2, 'room': 6},
 213: {'day': 0, 'hour': 3, 'room': 6},
 214: {'day': 0, 'hour': 4, 'room': 6},
 215: {'day': 0, 'hour': 5, 'room': 6},
 216: {'day': 0, 'hour': 6, 'room': 6},
 217: {'day': 1, 'hour': 0, 'room': 6},
 218: {'day': 1, 'hour': 1, 'room': 6},
 219: {'day': 1, 'hour': 2, 'room': 6},
 220: {'day': 1, 'hour': 3, 'room': 6},
 221: {'day': 1, 'hour': 4, 'room': 6},
 222: {'day': 1, 'hour': 5, 'room': 6},
 223: {'day': 1, 'hour': 6, 'room': 6},
 224: {'day': 2, 'hour': 0, 'room': 6},
 225: {'day': 2, 'hour': 1, 'room': 6},
 226: {'day': 2, 'hour': 2, 'room': 6},
 227: {'day': 2, 'hour': 3, 'room': 6},
 228: {'day': 2, 'hour': 4, 'room': 6},
 229: {'day': 2, 'hour': 5, 'room': 6},
 230: {'day': 2, 'hour': 6, 'room': 6},
 231: {'day': 3, 'hour': 0, 'room': 6},
 232: {'day': 3, 'hour': 1, 'room': 6},
 233: {'day': 3, 'hour': 2, 'room': 6},
 234: {'day': 3, 'hour': 3, 'room': 6},
 235: {'day': 3, 'hour': 4, 'room': 6},
 236: {'day': 3, 'hour': 5, 'room': 6},
 237: {'day': 3, 'hour': 6, 'room': 6},
 238: {'day': 4, 'hour': 0, 'room': 6},
 239: {'day': 4, 'hour': 1, 'room': 6},
 240: {'day': 4, 'hour': 2, 'room': 6},
 241: {'day': 4, 'hour': 3, 'room': 6},
 242: {'day': 4, 'hour': 4, 'room': 6},
 243: {'day': 4, 'hour': 5, 'room': 6},
 244: {'day': 4, 'hour': 6, 'room': 6},
 245: {'day': 0, 'hour': 0, 'room': 7},
 246: {'day': 0, 'hour': 1, 'room': 7},
 247: {'day': 0, 'hour': 2, 'room': 7},
 248: {'day': 0, 'hour': 3, 'room': 7},
 249: {'day': 0, 'hour': 4, 'room': 7},
 250: {'day': 0, 'hour': 5, 'room': 7},
 251: {'day': 0, 'hour': 6, 'room': 7},
 252: {'day': 1, 'hour': 0, 'room': 7},
 253: {'day': 1, 'hour': 1, 'room': 7},
 254: {'day': 1, 'hour': 2, 'room': 7},
 255: {'day': 1, 'hour': 3, 'room': 7},
 256: {'day': 1, 'hour': 4, 'room': 7},
 257: {'day': 1, 'hour': 5, 'room': 7},
 258: {'day': 1, 'hour': 6, 'room': 7},
 259: {'day': 2, 'hour': 0, 'room': 7},
 260: {'day': 2, 'hour': 1, 'room': 7},
 261: {'day': 2, 'hour': 2, 'room': 7},
 262: {'day': 2, 'hour': 3, 'room': 7},
 263: {'day': 2, 'hour': 4, 'room': 7},
 264: {'day': 2, 'hour': 5, 'room': 7},
 265: {'day': 2, 'hour': 6, 'room': 7},
 266: {'day': 3, 'hour': 0, 'room': 7},
 267: {'day': 3, 'hour': 1, 'room': 7},
 268: {'day': 3, 'hour': 2, 'room': 7},
 269: {'day': 3, 'hour': 3, 'room': 7},
 270: {'day': 3, 'hour': 4, 'room': 7},
 271: {'day': 3, 'hour': 5, 'room': 7},
 272: {'day': 3, 'hour': 6, 'room': 7},
 273: {'day': 4, 'hour': 0, 'room': 7},
 274: {'day': 4, 'hour': 1, 'room': 7},
 275: {'day': 4, 'hour': 2, 'room': 7},
 276: {'day': 4, 'hour': 3, 'room': 7},
 277: {'day': 4, 'hour': 4, 'room': 7},
 278: {'day': 4, 'hour': 5, 'room': 7},
 279: {'day': 4, 'hour': 6, 'room': 7},
 280: {'day': 0, 'hour': 0, 'room': 8},
 281: {'day': 0, 'hour': 1, 'room': 8},
 282: {'day': 0, 'hour': 2, 'room': 8},
 283: {'day': 0, 'hour': 3, 'room': 8},
 284: {'day': 0, 'hour': 4, 'room': 8},
 285: {'day': 0, 'hour': 5, 'room': 8},
 286: {'day': 0, 'hour': 6, 'room': 8},
 287: {'day': 1, 'hour': 0, 'room': 8},
 288: {'day': 1, 'hour': 1, 'room': 8},
 289: {'day': 1, 'hour': 2, 'room': 8},
 290: {'day': 1, 'hour': 3, 'room': 8},
 291: {'day': 1, 'hour': 4, 'room': 8},
 292: {'day': 1, 'hour': 5, 'room': 8},
 293: {'day': 1, 'hour': 6, 'room': 8},
 294: {'day': 2, 'hour': 0, 'room': 8},
 295: {'day': 2, 'hour': 1, 'room': 8},
 296: {'day': 2, 'hour': 2, 'room': 8},
 297: {'day': 2, 'hour': 3, 'room': 8},
 298: {'day': 2, 'hour': 4, 'room': 8},
 299: {'day': 2, 'hour': 5, 'room': 8},
 300: {'day': 2, 'hour': 6, 'room': 8},
 301: {'day': 3, 'hour': 0, 'room': 8},
 302: {'day': 3, 'hour': 1, 'room': 8},
 303: {'day': 3, 'hour': 2, 'room': 8},
 304: {'day': 3, 'hour': 3, 'room': 8},
 305: {'day': 3, 'hour': 4, 'room': 8},
 306: {'day': 3, 'hour': 5, 'room': 8},
 307: {'day': 3, 'hour': 6, 'room': 8},
 308: {'day': 4, 'hour': 0, 'room': 8},
 309: {'day': 4, 'hour': 1, 'room': 8},
 310: {'day': 4, 'hour': 2, 'room': 8},
 311: {'day': 4, 'hour': 3, 'room': 8},
 312: {'day': 4, 'hour': 4, 'room': 8},
 313: {'day': 4, 'hour': 5, 'room': 8},
 314: {'day': 4, 'hour': 6, 'room': 8},
 315: {'day': 0, 'hour': 0, 'room': 9},
 316: {'day': 0, 'hour': 1, 'room': 9},
 317: {'day': 0, 'hour': 2, 'room': 9},
 318: {'day': 0, 'hour': 3, 'room': 9},
 319: {'day': 0, 'hour': 4, 'room': 9},
 320: {'day': 0, 'hour': 5, 'room': 9},
 321: {'day': 0, 'hour': 6, 'room': 9},
 322: {'day': 1, 'hour': 0, 'room': 9},
 323: {'day': 1, 'hour': 1, 'room': 9},
 324: {'day': 1, 'hour': 2, 'room': 9},
 325: {'day': 1, 'hour': 3, 'room': 9},
 326: {'day': 1, 'hour': 4, 'room': 9},
 327: {'day': 1, 'hour': 5, 'room': 9},
 328: {'day': 1, 'hour': 6, 'room': 9},
 329: {'day': 2, 'hour': 0, 'room': 9},
 330: {'day': 2, 'hour': 1, 'room': 9},
 331: {'day': 2, 'hour': 2, 'room': 9},
 332: {'day': 2, 'hour': 3, 'room': 9},
 333: {'day': 2, 'hour': 4, 'room': 9},
 334: {'day': 2, 'hour': 5, 'room': 9},
 335: {'day': 2, 'hour': 6, 'room': 9},
 336: {'day': 3, 'hour': 0, 'room': 9},
 337: {'day': 3, 'hour': 1, 'room': 9},
 338: {'day': 3, 'hour': 2, 'room': 9},
 339: {'day': 3, 'hour': 3, 'room': 9},
 340: {'day': 3, 'hour': 4, 'room': 9},
 341: {'day': 3, 'hour': 5, 'room': 9},
 342: {'day': 3, 'hour': 6, 'room': 9},
 343: {'day': 4, 'hour': 0, 'room': 9},
 344: {'day': 4, 'hour': 1, 'room': 9},
 345: {'day': 4, 'hour': 2, 'room': 9},
 346: {'day': 4, 'hour': 3, 'room': 9},
 347: {'day': 4, 'hour': 4, 'room': 9},
 348: {'day': 4, 'hour': 5, 'room': 9},
 349: {'day': 4, 'hour': 6, 'room': 9},
 350: {'day': 0, 'hour': 0, 'room': 10},
 351: {'day': 0, 'hour': 1, 'room': 10},
 352: {'day': 0, 'hour': 2, 'room': 10},
 353: {'day': 0, 'hour': 3, 'room': 10},
 354: {'day': 0, 'hour': 4, 'room': 10},
 355: {'day': 0, 'hour': 5, 'room': 10},
 356: {'day': 0, 'hour': 6, 'room': 10},
 357: {'day': 1, 'hour': 0, 'room': 10},
 358: {'day': 1, 'hour': 1, 'room': 10},
 359: {'day': 1, 'hour': 2, 'room': 10},
 360: {'day': 1, 'hour': 3, 'room': 10},
 361: {'day': 1, 'hour': 4, 'room': 10},
 362: {'day': 1, 'hour': 5, 'room': 10},
 363: {'day': 1, 'hour': 6, 'room': 10},
 364: {'day': 2, 'hour': 0, 'room': 10},
 365: {'day': 2, 'hour': 1, 'room': 10},
 366: {'day': 2, 'hour': 2, 'room': 10},
 367: {'day': 2, 'hour': 3, 'room': 10},
 368: {'day': 2, 'hour': 4, 'room': 10},
 369: {'day': 2, 'hour': 5, 'room': 10},
 370: {'day': 2, 'hour': 6, 'room': 10},
 371: {'day': 3, 'hour': 0, 'room': 10},
 372: {'day': 3, 'hour': 1, 'room': 10},
 373: {'day': 3, 'hour': 2, 'room': 10},
 374: {'day': 3, 'hour': 3, 'room': 10},
 375: {'day': 3, 'hour': 4, 'room': 10},
 376: {'day': 3, 'hour': 5, 'room': 10},
 377: {'day': 3, 'hour': 6, 'room': 10},
 378: {'day': 4, 'hour': 0, 'room': 10},
 379: {'day': 4, 'hour': 1, 'room': 10},
 380: {'day': 4, 'hour': 2, 'room': 10},
 381: {'day': 4, 'hour': 3, 'room': 10},
 382: {'day': 4, 'hour': 4, 'room': 10},
 383: {'day': 4, 'hour': 5, 'room': 10},
 384: {'day': 4, 'hour': 6, 'room': 10},
 385: {'day': 0, 'hour': 0, 'room': 11},
 386: {'day': 0, 'hour': 1, 'room': 11},
 387: {'day': 0, 'hour': 2, 'room': 11},
 388: {'day': 0, 'hour': 3, 'room': 11},
 389: {'day': 0, 'hour': 4, 'room': 11},
 390: {'day': 0, 'hour': 5, 'room': 11},
 391: {'day': 0, 'hour': 6, 'room': 11},
 392: {'day': 1, 'hour': 0, 'room': 11},
 393: {'day': 1, 'hour': 1, 'room': 11},
 394: {'day': 1, 'hour': 2, 'room': 11},
 395: {'day': 1, 'hour': 3, 'room': 11},
 396: {'day': 1, 'hour': 4, 'room': 11},
 397: {'day': 1, 'hour': 5, 'room': 11},
 398: {'day': 1, 'hour': 6, 'room': 11},
 399: {'day': 2, 'hour': 0, 'room': 11},
 400: {'day': 2, 'hour': 1, 'room': 11},
 401: {'day': 2, 'hour': 2, 'room': 11},
 402: {'day': 2, 'hour': 3, 'room': 11},
 403: {'day': 2, 'hour': 4, 'room': 11},
 404: {'day': 2, 'hour': 5, 'room': 11},
 405: {'day': 2, 'hour': 6, 'room': 11},
 406: {'day': 3, 'hour': 0, 'room': 11},
 407: {'day': 3, 'hour': 1, 'room': 11},
 408: {'day': 3, 'hour': 2, 'room': 11},
 409: {'day': 3, 'hour': 3, 'room': 11},
 410: {'day': 3, 'hour': 4, 'room': 11},
 411: {'day': 3, 'hour': 5, 'room': 11},
 412: {'day': 3, 'hour': 6, 'room': 11},
 413: {'day': 4, 'hour': 0, 'room': 11},
 414: {'day': 4, 'hour': 1, 'room': 11},
 415: {'day': 4, 'hour': 2, 'room': 11},
 416: {'day': 4, 'hour': 3, 'room': 11},
 417: {'day': 4, 'hour': 4, 'room': 11},
 418: {'day': 4, 'hour': 5, 'room': 11},
 419: {'day': 4, 'hour': 6, 'room': 11},
 420: {'day': 0, 'hour': 0, 'room': 12},
 421: {'day': 0, 'hour': 1, 'room': 12},
 422: {'day': 0, 'hour': 2, 'room': 12},
 423: {'day': 0, 'hour': 3, 'room': 12},
 424: {'day': 0, 'hour': 4, 'room': 12},
 425: {'day': 0, 'hour': 5, 'room': 12},
 426: {'day': 0, 'hour': 6, 'room': 12},
 427: {'day': 1, 'hour': 0, 'room': 12},
 428: {'day': 1, 'hour': 1, 'room': 12},
 429: {'day': 1, 'hour': 2, 'room': 12},
 430: {'day': 1, 'hour': 3, 'room': 12},
 431: {'day': 1, 'hour': 4, 'room': 12},
 432: {'day': 1, 'hour': 5, 'room': 12},
 433: {'day': 1, 'hour': 6, 'room': 12},
 434: {'day': 2, 'hour': 0, 'room': 12},
 435: {'day': 2, 'hour': 1, 'room': 12},
 436: {'day': 2, 'hour': 2, 'room': 12},
 437: {'day': 2, 'hour': 3, 'room': 12},
 438: {'day': 2, 'hour': 4, 'room': 12},
 439: {'day': 2, 'hour': 5, 'room': 12},
 440: {'day': 2, 'hour': 6, 'room': 12},
 441: {'day': 3, 'hour': 0, 'room': 12},
 442: {'day': 3, 'hour': 1, 'room': 12},
 443: {'day': 3, 'hour': 2, 'room': 12},
 444: {'day': 3, 'hour': 3, 'room': 12},
 445: {'day': 3, 'hour': 4, 'room': 12},
 446: {'day': 3, 'hour': 5, 'room': 12},
 447: {'day': 3, 'hour': 6, 'room': 12},
 448: {'day': 4, 'hour': 0, 'room': 12},
 449: {'day': 4, 'hour': 1, 'room': 12},
 450: {'day': 4, 'hour': 2, 'room': 12},
 451: {'day': 4, 'hour': 3, 'room': 12},
 452: {'day': 4, 'hour': 4, 'room': 12},
 453: {'day': 4, 'hour': 5, 'room': 12},
 454: {'day': 4, 'hour': 6, 'room': 12}}

In [21]:
column_numbers

[24,
 38,
 10,
 30,
 63,
 16,
 12,
 54,
 59,
 48,
 17,
 65,
 29,
 14,
 5,
 35,
 18,
 37,
 13,
 50,
 64,
 55,
 0,
 25,
 19,
 32,
 4,
 11,
 33,
 31,
 39,
 42,
 22,
 9,
 60,
 34,
 40,
 44,
 43,
 57,
 2,
 27,
 21,
 46,
 47,
 49,
 1,
 53,
 26,
 28,
 52,
 51,
 66,
 67,
 61,
 56,
 20,
 62,
 45,
 6,
 36,
 8,
 41,
 58,
 15,
 23,
 3,
 7]

In [22]:
for column_number in column_numbers:
    print(columns[column_number])

{'lecturer': 6, 'student_group': 1, 'course': 'CSC504', 'subset': 'all'}
{'lecturer': 12, 'student_group': 1, 'course': 'CSL503', 'subset': 'batch', 'batch': 3}
{'lecturer': 3, 'student_group': 0, 'course': 'CSL302', 'subset': 'batch', 'batch': 1}
{'lecturer': 13, 'student_group': 1, 'course': 'CSL501', 'subset': 'batch', 'batch': 3}
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 3}
{'lecturer': 4, 'student_group': 0, 'course': 'CSL303', 'subset': 'batch', 'batch': 3}
{'lecturer': 3, 'student_group': 0, 'course': 'CSL302', 'subset': 'batch', 'batch': 3}
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 2}
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 3}
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
{'lecturer': 7, 'student_group': 0, 'course': 'CSL304', 'subset': 'batch', 'batch': 0}
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 1}
{'lecturer': 13, 'student_group': 1, 'course': 'CSL501', 'subset': 'batch', 'batch': 2}
{'lecturer': 4, 'student_group': 0, 'course': 'CSL303', 'subset': 'batch', 'batch': 1}
{'lecturer': 1, 'student_group': 0, 'course': 'CSL301', 'subset': 'batch', 'batch': 0}
{'lecturer': 12, 'student_group': 1, 'course': 'CSL503', 'subset': 'batch', 'batch': 0}
{'lecturer': 7, 'student_group': 0, 'course': 'CSL304', 'subset': 'batch', 'batch': 1}
{'lecturer': 12, 'student_group': 1, 'course': 'CSL503', 'subset': 'batch', 'batch': 2}
{'lecturer': 4, 'student_group': 0, 'course': 'CSL303', 'subset': 'batch', 'batch': 0}
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 0}
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 3}
{'lecturer': 0, 'student_group': 0, 'course': 'CSC301', 'subset': 'all'}
{'lecturer': 5, 'student_group': 1, 'course': 'CSC505', 'subset': 'all'}
{'lecturer': 7, 'student_group': 0, 'course': 'CSL304', 'subset': 'batch', 'batch': 2}
{'lecturer': 11, 'student_group': 1, 'course': 'CSL502', 'subset': 'batch', 'batch': 1}
{'lecturer': 4, 'student_group': 0, 'course': 'CSC305', 'subset': 'all'}
{'lecturer': 3, 'student_group': 0, 'course': 'CSL302', 'subset': 'batch', 'batch': 2}
{'lecturer': 11, 'student_group': 1, 'course': 'CSL502', 'subset': 'batch', 'batch': 2}
{'lecturer': 11, 'student_group': 1, 'course': 'CSL502', 'subset': 'batch', 'batch': 0}
{'lecturer': 7, 'student_group': 1, 'course': 'CSL504', 'subset': 'batch', 'batch': 0}
{'lecturer': 7, 'student_group': 1, 'course': 'CSL504', 'subset': 'batch', 'batch': 3}
{'lecturer': 2, 'student_group': 1, 'course': 'CSC502', 'subset': 'all'}
{'lecturer': 3, 'student_group': 0, 'course': 'CSL302', 'subset': 'batch', 'batch': 0}
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 0}
{'lecturer': 11, 'student_group': 1, 'course': 'CSL502', 'subset': 'batch', 'batch': 3}
{'lecturer': 7, 'student_group': 1, 'course': 'CSL504', 'subset': 'batch', 'batch': 1}
{'lecturer': 8, 'student_group': 1, 'course': 'CSL505', 'subset': 'batch', 'batch': 1}
{'lecturer': 8, 'student_group': 1, 'course': 'CSL505', 'subset': 'batch', 'batch': 0}
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 1}
{'lecturer': 2, 'student_group': 0, 'course': 'CSC303', 'subset': 'all'}
{'lecturer': 13, 'student_group': 1, 'course': 'CSL501', 'subset': 'batch', 'batch': 0}
{'lecturer': 5, 'student_group': 1, 'course': 'CSC501', 'subset': 'all'}
{'lecturer': 8, 'student_group': 1, 'course': 'CSL505', 'subset': 'batch', 'batch': 3}
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
{'lecturer': 1, 'student_group': 0, 'course': 'CSC302', 'subset': 'all'}
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 1}
{'lecturer': 9, 'student_group': 1, 'course': 'CSDLO5013', 'subset': 'all'}
{'lecturer': 13, 'student_group': 1, 'course': 'CSL501', 'subset': 'batch', 'batch': 1}
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 0}
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 2}
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 3}
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 1}
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 0}
{'lecturer': 7, 'student_group': 0, 'course': 'CSL304', 'subset': 'batch', 'batch': 3}
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 2}
{'lecturer': 8, 'student_group': 1, 'course': 'CSL505', 'subset': 'batch', 'batch': 2}
{'lecturer': 1, 'student_group': 0, 'course': 'CSL301', 'subset': 'batch', 'batch': 1}
{'lecturer': 12, 'student_group': 1, 'course': 'CSL503', 'subset': 'batch', 'batch': 1}
{'lecturer': 1, 'student_group': 0, 'course': 'CSL301', 'subset': 'batch', 'batch': 3}
{'lecturer': 7, 'student_group': 1, 'course': 'CSL504', 'subset': 'batch', 'batch': 2}
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 2}
{'lecturer': 4, 'student_group': 0, 'course': 'CSL303', 'subset': 'batch', 'batch': 2}
{'lecturer': 6, 'student_group': 1, 'course': 'CSC503', 'subset': 'all'}
{'lecturer': 3, 'student_group': 0, 'course': 'CSC304', 'subset': 'all'}
{'lecturer': 1, 'student_group': 0, 'course': 'CSL301', 'subset': 'batch', 'batch': 2}

In [23]:
course_dictionary['CSC301'].no_of_hours_to_schedule_when_assigning

1

In [24]:
room_dictionary = {}
for room in rooms_list:
    room_dictionary[room.id] = room

In [25]:
def no_batch_conflicts(target_matrix, rows, columns, day, hour, batch, student_group_id, course_id, lecturer_id):
    for i in range(len(rows)):
        current_day = rows[i]["day"]
        current_hour = rows[i]["hour"]
        if current_day == day and current_hour == hour:
            for j in range(len(columns)):
                if columns[j]["subset"] == "batch" and columns[j]["student_group"] == student_group_id and target_matrix[i][j]==1:
                    if columns[j]["batch"] == batch or columns[j]["lecturer"] == lecturer_id or columns[j]["course"]==course_id: 
                        return False
    return True

In [26]:
def getValidDays(no_of_days, rows, columns, target_matrix, lecturer_id, course_id, lecturer_max_no_hours_per_day, course_max_no_hours_per_day):
    day_flag = [False] * no_of_days
    for day in range(no_of_days):
        course_count = 0
        lecturer_count = 0 
        for i in range(len(rows)):
            for j in range(len(columns)):
                if target_matrix[i][j] == 1:
                    if rows[i]["day"] == day and columns[j]["lecturer"] == lecturer_id:
                        lecturer_count+=1
                    if rows[i]["day"] == day and columns[j]["course"] == course_id:
                        course_count+=1
        if lecturer_max_no_hours_per_day > lecturer_count and course_max_no_hours_per_day > course_count:
            day_flag[day] = True 
    return day_flag

In [27]:
def getValidRows(rows, target_matrix, column_number, day_flag, room_dictionary, valid_rooms, no_of_hours_to_schedule_when_assigning, lecturer_availability, no_of_hours):
    valid_rows = []
    for i in range(len(rows)):
        day = rows[i]["day"]
        hour = rows[i]["hour"]
        if target_matrix[i][column_number] == 0 and day_flag[day]:
            if room_dictionary[rows[i]["room"]].name in valid_rooms:
                flag = True
                for j in range(no_of_hours_to_schedule_when_assigning):
                    if rows[i]['hour'] + j != rows[i+j]['hour'] or lecturer_availability[day*no_of_hours+hour+j] != 1 or target_matrix[i+j][column_number]!=0:
                        flag = False
                        break
                if flag:
                    valid_rows.append(i)
    return valid_rows

In [28]:
def scheduleCourse(valid_rows, no_of_hours_to_schedule_when_assigning, rows, columns, target_matrix, lecturer_id, student_group_id, column_number):
    row_id_to_schedule = random.choice(valid_rows)
    no_of_hours_scheduled = 0
    for k in range(no_of_hours_to_schedule_when_assigning):
        day = rows[row_id_to_schedule+k]["day"]
        hour = rows[row_id_to_schedule+k]["hour"]
        room = rows[row_id_to_schedule+k]["room"]
#         print(day, hour,room_dictionary[room].name)

        for j in range(len(columns)):
            target_matrix[row_id_to_schedule+k][j] = -1

        for i in range(len(rows)):
            for j in range(len(columns)):
                if rows[i]["day"] == day and rows[i]["hour"] == hour and columns[j]["lecturer"] == lecturer_id and target_matrix[i][j]!=1:
                    target_matrix[i][j] = -1
                if rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["student_group"] == student_group_id and target_matrix[i][j]!=1:
                    target_matrix[i][j] = -1   
        target_matrix[row_id_to_schedule+k][column_number] = 1
        no_of_hours_scheduled+=1
    return target_matrix, no_of_hours_scheduled

In [29]:
def scheduleBatchCourse(row_id_to_schedule, no_of_hours_to_schedule_when_assigning, rows, columns, target_matrix, lecturer_id, student_group_id, batch, column_number):
    no_of_hours_scheduled = 0
    for k in range(no_of_hours_to_schedule_when_assigning):
        day = rows[row_id_to_schedule+k]["day"]
        hour = rows[row_id_to_schedule+k]["hour"]
        room = rows[row_id_to_schedule+k]["room"]
#         print(day, hour, room)
        for j in range(len(columns)):
            target_matrix[row_id_to_schedule+k][j] = -1
        for i in range(len(rows)):
            for j in range(len(columns)):
                if rows[i]["day"] == day and rows[i]["hour"] == hour and columns[j]["lecturer"] == lecturer_id and target_matrix[i][j]!=1:
                    target_matrix[i][j] = -1
                elif rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["student_group"] == student_group_id and columns[n]["subset"] == "all" and target_matrix[i][j]!=1:
                    target_matrix[i][j] = -1
                elif rows[i]["day"] == day and rows[i]["hour"]== hour and columns[j]["student_group"] == student_group_id and columns[j]["subset"] == "batch" and columns[j]["batch"] == batch and target_matrix[i][j]!=1:
                    target_matrix[i][j] = -1
        target_matrix[row_id_to_schedule+k][column_number] = 1
        no_of_hours_scheduled+=1
    return target_matrix, no_of_hours_scheduled

In [30]:
import numpy as np
def fillTargetMatrix(column_numbers, columns, hours_for_columns, rows, day_dictionary, hour_dictionary, room_dictionary, lecturer_dictionary, student_group_dictionary, course_dictionary, no_of_days, no_of_hours, total_hours):
    target_matrix = np.zeros((len(rows), len(columns)))
    no_hours_not_scheduled = 0
    for column_number in column_numbers:
#         print(column_number)
        if columns[column_number]["subset"] == "all":
#             if input("all") == "N":
#                 return target_matrix
            course_id = columns[column_number]['course']
            lecturer_id = columns[column_number]['lecturer']
            student_group_id = columns[column_number]['student_group']
            no_of_hours_to_schedule = hours_for_columns[column_number]
            no_of_hours_to_schedule_when_assigning = course_dictionary[course_id].no_of_hours_to_schedule_when_assigning
            while no_of_hours_to_schedule > 0:
                day_flag = getValidDays(no_of_days, rows, columns, target_matrix, lecturer_id, course_id,lecturer_dictionary[lecturer_id].max_no_hours_per_day, course_dictionary[course_id].max_no_hours_per_day)
                # For Valid rows following conditions:
                # 1. Check if slot is free, i.e. 0
                # 2. Check room validity using atribute valid_rooms in 'Course' object
                # 3. Check Hour and Day validity using attribute availability in 'Lecturer' object
                valid_rows = getValidRows(rows, target_matrix, column_number, day_flag, room_dictionary, course_dictionary[course_id].valid_rooms, no_of_hours_to_schedule_when_assigning, lecturer_dictionary[lecturer_id].availability, no_of_hours)
#                 for i in range(len(rows)):
#                     day = rows[i]["day"]
#                     hour = rows[i]["hour"]
#                     if target_matrix[i][column_number] == 0 and day_flag[day]:
#                         if room_dictionary[rows[i]["room"]].name in course_dictionary[course_id].valid_rooms:
#                             flag = True
#                             for j in range(no_of_hours_to_schedule_when_assigning):
#                                 if rows[i]['hour'] + j != rows[i+j]['hour'] or lecturer_dictionary[lecturer_id].availability[day*no_of_hours+hour+j] != 1 or target_matrix[i+j][column_number]!=0:
#                                     flag = False
#                                     break
#                             if flag:
#                                 valid_rows.append(i)


                # 4. Check max no of hours per day of Course and Lecturer
                # 5. Check max consecutive hours of Course and Lecturer
                if len(valid_rows) == 0:
#                     print("COULD NOT SCHEDULE")
                    no_hours_not_scheduled += no_of_hours_to_schedule
#                     print(column_number, no_of_hours_to_schedule)
                    break
#                 print(valid_rows)
                target_matrix, no_of_hours_scheduled = scheduleCourse(valid_rows, no_of_hours_to_schedule_when_assigning, rows, columns, target_matrix, lecturer_id, student_group_id, column_number)
                no_of_hours_to_schedule -= no_of_hours_scheduled
                # Bottom Line randomly chooses row to schedule
#                 row_id_to_schedule = random.choice(valid_rows)
#                 # Bottom Line chooses first element
# #                 row_id_to_schedule = valid_rows[0]
#                 for k in range(no_of_hours_to_schedule_when_assigning):
#                     day = rows[row_id_to_schedule+k]["day"]
#                     hour = rows[row_id_to_schedule+k]["hour"]
#                     room = rows[row_id_to_schedule+k]["room"]
#                     print(day, hour,room_dictionary[room].name)

#                     for j in range(len(columns)):
#                         target_matrix[row_id_to_schedule+k][j] = -1

#                     for i in range(len(rows)):
#                         for j in range(len(columns)):
#                             if rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["lecturer"] == lecturer_id and target_matrix[i][j]!=1:
#                                 target_matrix[i][j] = -1
#                             if rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["student_group"] == student_group_id and target_matrix[i][j]!=1:
#                                 target_matrix[i][j] = -1   
#                     target_matrix[row_id_to_schedule+k][column_number] = 1
#                     no_of_hours_to_schedule-=1
        else:
            #Check if another lab has been scheduled, and schedule it at that day and hour if possible.
#             if input("batch") == "N":
#                 return target_matrix
            course_id = columns[column_number]['course']
            lecturer_id = columns[column_number]['lecturer']
            student_group_id = columns[column_number]['student_group']
            no_of_hours_to_schedule = hours_for_columns[column_number]
            batch = columns[column_number]["batch"]
            no_of_hours_to_schedule_when_assigning = course_dictionary[course_id].no_of_hours_to_schedule_when_assigning
            while no_of_hours_to_schedule>0:
                #Find all day and hour available
                day_flag = getValidDays(no_of_days, rows, columns, target_matrix, lecturer_id, course_id, lecturer_dictionary[lecturer_id].max_no_hours_per_day, course_dictionary[course_id].max_no_hours_per_day)
                valid_rows = getValidRows(rows, target_matrix, column_number, day_flag, room_dictionary, course_dictionary[course_id].valid_rooms, no_of_hours_to_schedule_when_assigning, lecturer_dictionary[lecturer_id].availability, no_of_hours)
#                 for i in range(len(rows)):
#                     day = rows[i]["day"]
#                     hour = rows[i]["hour"]
#                     if room_dictionary[rows[i]["room"]].name in course_dictionary[course_id].valid_rooms:
#                         flag = True
#                         for j in range(no_of_hours_to_schedule_when_assigning):
#                             if rows[i]['hour'] + j != rows[i+j]['hour'] or lecturer_dictionary[lecturer_id].availability[day*no_of_hours+hour+j] != 1 or target_matrix[i+j][column_number]!=0:
# #                                 if target_matrix[i+j][column_number]!=0:
#                                 flag = False
#                                 break
#                         if flag:
#                             valid_rows.append(i)
                if len(valid_rows) == 0:
#                     print("COULD NOT SCHEDULE")
                    no_hours_not_scheduled += no_of_hours_to_schedule
#                     print(column_number, no_of_hours_to_schedule)
                    break
#                 print(valid_rows)
#                 if input() == "N": 
#                     return target_matrix
                #Valid Rows contains all index that are possible to be scheduled
                scheduled_flag = False
                for i in range(len(rows)):
                    day = rows[i]["day"]
                    hour = rows[i]["hour"]
                    for j in range(len(columns)):
                        #Not checking all batches
                        if columns[j]["subset"] == "batch" and columns[j]["student_group"] == student_group_id:
                            if columns[j]["batch"]!=batch and columns[j]["course"]!=course_id and target_matrix[i][j]==1:
                                batch_has_not_been_scheduled_flag = True
                                if no_batch_conflicts(target_matrix, rows, columns, day, hour, batch, student_group_id, course_id, lecturer_id):
                                    for o in valid_rows:
                                        if rows[o]["day"] == day and rows[o]["hour"] == hour and target_matrix[o][column_number]==0:
#                                             print(o)
#                                             print("#Schedule Here")
                                            for k in range(no_of_hours_to_schedule_when_assigning):
#                                                 print(rows[o+k]["day"], rows[o+k]["hour"], room_dictionary[rows[o+k]["room"]].name)
                                                for l in range(len(columns)):
                                                    target_matrix[o+k][l] = -1
                                                #Make unavailable room and lecturer for same day and time
                                                for m in range(len(rows)):
                                                    for n in range(len(columns)):
                                                        if rows[m]["day"] == rows[o+k]["day"] and rows[m]["hour"]==rows[o+k]["hour"] and columns[n]["lecturer"] == lecturer_id and target_matrix[m][n]!=1:
                                                            target_matrix[m][n] = -1
                                                        if rows[m]["day"] == rows[o+k]["day"] and rows[m]["hour"]==rows[o+k]["hour"] and columns[n]["student_group"] == student_group_id and columns[n]["subset"] == "all" and target_matrix[m][n]!=1:
                                                            target_matrix[m][n] = -1
                                                        if rows[m]["day"] == rows[o+k]["day"] and rows[m]["hour"]==rows[o+k]["hour"] and columns[n]["student_group"] == student_group_id and columns[n]["subset"] == "batch" and columns[n]["batch"] == batch and target_matrix[m][n]!=1:
                                                            target_matrix[m][n] = -1
                                                            
                                                target_matrix[o+k][column_number] = 1
                                                scheduled_flag = True
                                                no_of_hours_to_schedule-=1
#                                             target_matrix, no_of_hours_scheduled = scheduleBatchCourse(o, no_of_hours_to_schedule_when_assigning, rows, columns, target_matrix, lecturer_id, student_group_id, batch, column_number)
#                                             scheduled_flag = True
#                                             no_of_hours_to_schedule -= no_of_hours_scheduled
                                            break
                                if scheduled_flag:
                                    break
                            if scheduled_flag:
                                break
                            
                #Else Randomly Schedule        
                if scheduled_flag == False:
#                     print("Randomly Schedule ")
                    #Schedule new
                    row_id_to_schedule = random.choice(valid_rows)
                    # Bottom Line chooses first element
    #                 row_id_to_schedule = valid_rows[0]
                    scheduled_rows = []
                    for k in range(no_of_hours_to_schedule_when_assigning):
                        day = rows[row_id_to_schedule+k]["day"]
                        hour = rows[row_id_to_schedule+k]["hour"]
#                         print(day, hour, room_dictionary[rows[row_id_to_schedule+k]["room"]].name)
#                         if input() == "N":
#                             return target_matrix

                        for j in range(len(columns)):
                            target_matrix[row_id_to_schedule+k][j] = -1

                        for i in range(len(rows)):
                            for j in range(len(columns)):
                                if i not in scheduled_rows:
                                    if rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["lecturer"] == lecturer_id and target_matrix[i][j]!=1:
                                        target_matrix[i][j] = -1
                                    if rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["student_group"] == student_group_id and columns[j]["subset"] == "all" and target_matrix[i][j]!=1:
                                        target_matrix[i][j] = -1
                                    if rows[i]["day"] == day and rows[i]["hour"]==hour and columns[j]["student_group"] == student_group_id and columns[j]["subset"] == "batch" and columns[j]["batch"] == batch and target_matrix[i][j]!=1:
                                        target_matrix[i][j] = -1
                        
                        target_matrix[row_id_to_schedule+k][column_number] = 1
                        scheduled_rows.append(row_id_to_schedule+k)
                        no_of_hours_to_schedule-=1
                
    return target_matrix, 100 - (no_hours_not_scheduled * 100)/total_hours

In [246]:
random.shuffle(column_numbers)
target_matrix, fitness = fillTargetMatrix(column_numbers, columns, hours_for_columns, rows, day_dictionary, hour_dictionary, room_dictionary, lecturer_dictionary, student_group_dictionary, course_dictionary, no_of_days, no_of_hours, total_hours)

In [247]:
fitness

92.45283018867924

In [73]:
total_sum = 0
for j in range(len(columns)):
    sum = 0
    for i in range(len(rows)):
        if target_matrix[i][j] > 0:
            sum += target_matrix[i][j]
    total_sum+=sum
    print(sum, hours_for_columns[j])
print(total_sum)

5.0 5
4.0 4
4.0 4
4.0 4
4.0 4
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
4.0 4
4.0 4
4.0 4
4.0 4
2.0 2
4.0 4
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
4.0 4
4.0 4
4.0 4
4.0 4
3.0 3
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
2.0 2
166.0

In [133]:
import pandas as pd

In [134]:
student_group = 2
count = 1
weekdays = ["Mon", "Tue", "Wed", "Thur", "Fri"]
lectures = []
for i in range(len(rows)):
    for j in range(len(columns)):
        if columns[j]["student_group"] == student_group and target_matrix[i][j]==1:
            lectures.append((i, j))

In [135]:
lectures

[(71, 47),
 (72, 47),
 (75, 51),
 (76, 48),
 (77, 48),
 (78, 51),
 (79, 49),
 (80, 47),
 (81, 48),
 (82, 49),
 (83, 50),
 (85, 50),
 (90, 50),
 (91, 50),
 (92, 49),
 (98, 48),
 (101, 47),
 (103, 51),
 (104, 49),
 (108, 55),
 (109, 55),
 (121, 52),
 (122, 52),
 (129, 53),
 (130, 53),
 (134, 54),
 (135, 54),
 (178, 60),
 (179, 60),
 (191, 61),
 (192, 61),
 (201, 62),
 (202, 62),
 (204, 63),
 (205, 63),
 (283, 57),
 (284, 57),
 (296, 58),
 (297, 58),
 (306, 59),
 (307, 59),
 (309, 56),
 (310, 56),
 (353, 66),
 (354, 66),
 (366, 67),
 (367, 67),
 (376, 64),
 (377, 64),
 (379, 65),
 (380, 65)]

In [136]:
slots = {}
elements = []
for day in range(no_of_days):
    for hour in range(no_of_hours):
        flag = False
        for lecture in lectures:
            if rows[lecture[0]]['day'] == day and rows[lecture[0]]['hour'] == hour:
                flag = True
#                 if hour in slots:
                elements.append((columns[lecture[1]], day, hour))
                print(columns[lecture[1]], day, hour)
#                     slots[hour].append(str(columns[le]))
                if hour in slots:
                    slots[hour].append(columns[lecture[1]])
                else:
                    slots[hour] = [columns[lecture[1]]]
        if flag == False:
            if hour in slots:
                    slots[hour].append("Free")
            else:
                slots[hour] = ["Free"]

{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'} 0 1
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'} 0 2
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 3} 0 3
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 0} 0 3
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 1} 0 3
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 2} 0 3
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 3} 0 4
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 0} 0 4
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 1} 0 4
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 2} 0 4
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'} 0 5
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'} 0 6
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'} 1 0
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'} 1 1
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'} 1 2
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'} 1 3
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'} 1 4
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'} 1 5
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'} 1 6
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'} 2 1
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 0} 2 2
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 1} 2 2
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 2} 2 2
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 3} 2 2
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 0} 2 3
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 1} 2 3
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 2} 2 3
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 3} 2 3
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'} 2 6
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'} 3 0
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'} 3 1
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 1} 3 3
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 1} 3 4
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 2} 3 5
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 3} 3 5
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 0} 3 5
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 2} 3 6
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 3} 3 6
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 0} 3 6
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'} 4 0
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 2} 4 1
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 3} 4 1
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 0} 4 1
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 1} 4 1
{'lecturer': 8, 'student_group': 2, 'course': 'CSL701', 'subset': 'batch', 'batch': 2} 4 2
{'lecturer': 11, 'student_group': 2, 'course': 'CSL703', 'subset': 'batch', 'batch': 3} 4 2
{'lecturer': 12, 'student_group': 2, 'course': 'CSL702', 'subset': 'batch', 'batch': 0} 4 2
{'lecturer': 13, 'student_group': 2, 'course': 'CSL704', 'subset': 'batch', 'batch': 1} 4 2
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'} 4 3
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'} 4 5
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'} 4 6

In [137]:
labs = {}
for element in elements:
    if element[0]["subset"] == "batch":
        day = element[1]
        hour = element[2]
        if str(day)+","+str(hour) in labs:
            labs[str(day)+","+str(hour)].append(element[0])
            
        else:
            labs[str(day)+","+str(hour)] = [element[0]]

In [138]:
test = {}
for lab in labs:
    string = ""
    for slot in labs[lab]:
        string += "Lecturer: "+str(lecturer_dictionary[slot["lecturer"]].name)+" Course: "+str(slot["course"])+" Batch: "+str(slot["batch"]) + " \n"
    test[lab] = string

In [139]:
test

{'0,3': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 3 \nLecturer: Shafaque Course: CSL703 Batch: 0 \nLecturer: Phiroj Course: CSL702 Batch: 1 \nLecturer: Sana Course: CSL704 Batch: 2 \n',
 '0,4': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 3 \nLecturer: Shafaque Course: CSL703 Batch: 0 \nLecturer: Phiroj Course: CSL702 Batch: 1 \nLecturer: Sana Course: CSL704 Batch: 2 \n',
 '2,2': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 0 \nLecturer: Shafaque Course: CSL703 Batch: 1 \nLecturer: Phiroj Course: CSL702 Batch: 2 \nLecturer: Sana Course: CSL704 Batch: 3 \n',
 '2,3': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 0 \nLecturer: Shafaque Course: CSL703 Batch: 1 \nLecturer: Phiroj Course: CSL702 Batch: 2 \nLecturer: Sana Course: CSL704 Batch: 3 \n',
 '3,3': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n',
 '3,4': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n',
 '3,5': 'Lecturer: Shafaque Course: CSL703 Batch: 2 \nLecturer: Phiroj Course: CSL702 Batch: 3 \nLecturer: Sana Course: CSL704 Batch: 0 \n',
 '3,6': 'Lecturer: Shafaque Course: CSL703 Batch: 2 \nLecturer: Phiroj Course: CSL702 Batch: 3 \nLecturer: Sana Course: CSL704 Batch: 0 \n',
 '4,1': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 2 \nLecturer: Shafaque Course: CSL703 Batch: 3 \nLecturer: Phiroj Course: CSL702 Batch: 0 \nLecturer: Sana Course: CSL704 Batch: 1 \n',
 '4,2': 'Lecturer: Dipti Jadhav Course: CSL701 Batch: 2 \nLecturer: Shafaque Course: CSL703 Batch: 3 \nLecturer: Phiroj Course: CSL702 Batch: 0 \nLecturer: Sana Course: CSL704 Batch: 1 \n'}

In [140]:
student_group = 2
count = 1
weekdays = ["Mon", "Tue", "Wed", "Thur", "Fri"]
lectures = []
for i in range(len(rows)):
    for j in range(len(columns)):
        if columns[j]["student_group"] == student_group and target_matrix[i][j]==1 and columns[j]["subset"] == "all":
            lectures.append((i, j))

In [141]:
lectures

[(71, 47),
 (72, 47),
 (75, 51),
 (76, 48),
 (77, 48),
 (78, 51),
 (79, 49),
 (80, 47),
 (81, 48),
 (82, 49),
 (83, 50),
 (85, 50),
 (90, 50),
 (91, 50),
 (92, 49),
 (98, 48),
 (101, 47),
 (103, 51),
 (104, 49)]

In [142]:
slots = {}
for day in range(no_of_days):
    for hour in range(no_of_hours):
        print(day, hour)
        flag = False
        for lecture in lectures:
            if rows[lecture[0]]['day'] == day and rows[lecture[0]]['hour'] == hour:
                flag = True
#                 if hour in slots:
                print(columns[lecture[1]])
#                     slots[hour].append(str(columns[le]))
                if hour in slots:
                    slots[hour].append(columns[lecture[1]])
                else:
                    slots[hour] = [columns[lecture[1]]]
        if flag == False:
            if str(day)+","+str(hour) in test:
                print(test[str(day)+","+str(hour)])
                if hour in slots:
                    slots[hour].append(test[str(day)+","+str(hour)])
                else:
                    slots[hour] = [test[str(day)+","+str(hour)]]
            elif hour in slots:
                slots[hour].append("Free")
            else:
                slots[hour] = ["Free"]

0 0
0 1
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
0 2
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
0 3
Lecturer: Dipti Jadhav Course: CSL701 Batch: 3
Lecturer: Shafaque Course: CSL703 Batch: 0
Lecturer: Phiroj Course: CSL702 Batch: 1
Lecturer: Sana Course: CSL704 Batch: 2

0 4
Lecturer: Dipti Jadhav Course: CSL701 Batch: 3
Lecturer: Shafaque Course: CSL703 Batch: 0
Lecturer: Phiroj Course: CSL702 Batch: 1
Lecturer: Sana Course: CSL704 Batch: 2

0 5
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
0 6
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
1 0
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
1 1
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
1 2
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
1 3
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
1 4
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
1 5
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
1 6
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
2 0
2 1
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
2 2
Lecturer: Dipti Jadhav Course: CSL701 Batch: 0
Lecturer: Shafaque Course: CSL703 Batch: 1
Lecturer: Phiroj Course: CSL702 Batch: 2
Lecturer: Sana Course: CSL704 Batch: 3

2 3
Lecturer: Dipti Jadhav Course: CSL701 Batch: 0
Lecturer: Shafaque Course: CSL703 Batch: 1
Lecturer: Phiroj Course: CSL702 Batch: 2
Lecturer: Sana Course: CSL704 Batch: 3

2 4
2 5
2 6
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
3 0
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
3 1
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
3 2
3 3
Lecturer: Dipti Jadhav Course: CSL701 Batch: 1

3 4
Lecturer: Dipti Jadhav Course: CSL701 Batch: 1

3 5
Lecturer: Shafaque Course: CSL703 Batch: 2
Lecturer: Phiroj Course: CSL702 Batch: 3
Lecturer: Sana Course: CSL704 Batch: 0

3 6
Lecturer: Shafaque Course: CSL703 Batch: 2
Lecturer: Phiroj Course: CSL702 Batch: 3
Lecturer: Sana Course: CSL704 Batch: 0

4 0
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
4 1
Lecturer: Dipti Jadhav Course: CSL701 Batch: 2
Lecturer: Shafaque Course: CSL703 Batch: 3
Lecturer: Phiroj Course: CSL702 Batch: 0
Lecturer: Sana Course: CSL704 Batch: 1

4 2
Lecturer: Dipti Jadhav Course: CSL701 Batch: 2
Lecturer: Shafaque Course: CSL703 Batch: 3
Lecturer: Phiroj Course: CSL702 Batch: 0
Lecturer: Sana Course: CSL704 Batch: 1

4 3
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
4 4
4 5
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
4 6
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}

In [143]:
for slot in slots:
    list_of_slot = slots[slot]
#     print(list_of_slot)
    temp_list = []
    for i in range(len(list_of_slot)):
        print(list_of_slot[i])
        if list_of_slot[i] is "Free":
            temp_list.append("Free")
        elif "Lecturer" in list_of_slot[i]:
            temp_list.append(list_of_slot[i])
        else:
            temp_lecturer = list_of_slot[i]["lecturer"]
            temp_course = list_of_slot[i]["course"]
            string = ""
            for lecturer in lecturer_list:
                if lecturer.id == temp_lecturer:
                    string+=lecturer.name + " "

            for course in course_list:
                if course.id == temp_course:
                    string+=course.name + " "
            print(string)
            temp_list.append(string)
    slots[slot] = temp_list

Free
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
Amiya Kumar Tripathy MCC
Free
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
Others Dept Level Elective
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
Amiya Kumar Tripathy MCC
{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
Dipti Jadhav DSIP
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
Others Inst Level Elective
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
Others Dept Level Elective
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
Kalpita Wagaskar AISC
Lecturer: Dipti Jadhav Course: CSL701 Batch: 2
Lecturer: Shafaque Course: CSL703 Batch: 3
Lecturer: Phiroj Course: CSL702 Batch: 0
Lecturer: Sana Course: CSL704 Batch: 1

{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
Dipti Jadhav DSIP
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
Kalpita Wagaskar AISC
Lecturer: Dipti Jadhav Course: CSL701 Batch: 0
Lecturer: Shafaque Course: CSL703 Batch: 1
Lecturer: Phiroj Course: CSL702 Batch: 2
Lecturer: Sana Course: CSL704 Batch: 3

Free
Lecturer: Dipti Jadhav Course: CSL701 Batch: 2
Lecturer: Shafaque Course: CSL703 Batch: 3
Lecturer: Phiroj Course: CSL702 Batch: 0
Lecturer: Sana Course: CSL704 Batch: 1

Lecturer: Dipti Jadhav Course: CSL701 Batch: 3
Lecturer: Shafaque Course: CSL703 Batch: 0
Lecturer: Phiroj Course: CSL702 Batch: 1
Lecturer: Sana Course: CSL704 Batch: 2

{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
Dipti Jadhav DSIP
Lecturer: Dipti Jadhav Course: CSL701 Batch: 0
Lecturer: Shafaque Course: CSL703 Batch: 1
Lecturer: Phiroj Course: CSL702 Batch: 2
Lecturer: Sana Course: CSL704 Batch: 3

Lecturer: Dipti Jadhav Course: CSL701 Batch: 1

{'lecturer': 8, 'student_group': 2, 'course': 'CSC701', 'subset': 'all'}
Dipti Jadhav DSIP
Lecturer: Dipti Jadhav Course: CSL701 Batch: 3
Lecturer: Shafaque Course: CSL703 Batch: 0
Lecturer: Phiroj Course: CSL702 Batch: 1
Lecturer: Sana Course: CSL704 Batch: 2

{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
Amiya Kumar Tripathy MCC
Free
Lecturer: Dipti Jadhav Course: CSL701 Batch: 1

Free
{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
Others Inst Level Elective
{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
Kalpita Wagaskar AISC
Free
Lecturer: Shafaque Course: CSL703 Batch: 2
Lecturer: Phiroj Course: CSL702 Batch: 3
Lecturer: Sana Course: CSL704 Batch: 0

{'lecturer': 10, 'student_group': 2, 'course': 'ILO70XX', 'subset': 'all'}
Others Inst Level Elective
{'lecturer': 7, 'student_group': 2, 'course': 'CSC702', 'subset': 'all'}
Amiya Kumar Tripathy MCC
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
Others Dept Level Elective
{'lecturer': 10, 'student_group': 2, 'course': 'CSDL70X', 'subset': 'all'}
Others Dept Level Elective
Lecturer: Shafaque Course: CSL703 Batch: 2
Lecturer: Phiroj Course: CSL702 Batch: 3
Lecturer: Sana Course: CSL704 Batch: 0

{'lecturer': 9, 'student_group': 2, 'course': 'CSC703', 'subset': 'all'}
Kalpita Wagaskar AISC

In [144]:
slots["weekdays"] = weekdays

In [145]:
df = pd.DataFrame(slots)

In [173]:
df.set_index('weekdays')

,0,1,2,3,4,5,6
weekdays,,,,,,,
Mon,Free,Dipti Jadhav DSIP,Dipti Jadhav DSIP,Lecturer: Dipti Jadhav Course: CSL701 Batch: 3...,Lecturer: Dipti Jadhav Course: CSL701 Batch: 3...,Others Inst Level Elective,Amiya Kumar Tripathy MCC
Tue,Amiya Kumar Tripathy MCC,Others Inst Level Elective,Kalpita Wagaskar AISC,Dipti Jadhav DSIP,Amiya Kumar Tripathy MCC,Kalpita Wagaskar AISC,Others Dept Level Elective
Wed,Free,Others Dept Level Elective,Lecturer: Dipti Jadhav Course: CSL701 Batch: 0...,Lecturer: Dipti Jadhav Course: CSL701 Batch: 0...,Free,Free,Others Dept Level Elective
Thur,Others Dept Level Elective,Kalpita Wagaskar AISC,Free,Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n,Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n,Lecturer: Shafaque Course: CSL703 Batch: 2 \nL...,Lecturer: Shafaque Course: CSL703 Batch: 2 \nL...
Fri,Amiya Kumar Tripathy MCC,Lecturer: Dipti Jadhav Course: CSL701 Batch: 2...,Lecturer: Dipti Jadhav Course: CSL701 Batch: 2...,Dipti Jadhav DSIP,Free,Others Inst Level Elective,Kalpita Wagaskar AISC

In [186]:
df[4][3]

'Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n'

In [ ]:
df.to_excel("output.xlsx", sheet_name="Sheet3")

In [94]:
"Lecturer" in "Lecturer: 1 Course: CSL301 Batch: 1 \nLecturer: 3 Course: CSL302 Batch: 0 \nLecturer: 4 Course: CSL303 Batch: 3 \nLecturer: 7 Course: CSL304 Batch: 2 \n"

True

In [117]:
BE = df

In [103]:
TE = df

In [88]:
SE = df

In [118]:
from pandas import ExcelWriter

In [119]:
list_dfs = [SE]
list_dfs.append(TE)
list_dfs.append(BE)
list_dfs

[                                                   0  \
 0                                Ali Imran Mirza DS
 1                          REVATHY SUNDARARAJAN AM
 2  Lecturer: Deepali Kayande Course: CSL301 Batch...
 3                                 Sejal Chopra ECCF
 4                                     Priya Kaul DM

                                                    1  \
 0                                Ali Imran Mirza DS
 1  Lecturer: Deepali Kayande Course: CSL301 Batch...
 2  Lecturer: Deepali Kayande Course: CSL301 Batch...
 3  Lecturer: Deepali Kayande Course: CSL301 Batch...
 4                          REVATHY SUNDARARAJAN AM

                                                    2  \
 0                                               Free
 1  Lecturer: Deepali Kayande Course: CSL301 Batch...
 2                                 Sejal Chopra ECCF
 3  Lecturer: Deepali Kayande Course: CSL301 Batch...
 4                                Ali Imran Mirza DS

                                                    3  \
 0  Lecturer: Sejal Chopra Course: CSL302 Batch: 0...
 1                                     Priya Kaul DM
 2                                     Priya Kaul DM
 3                              Deepali Kayande DLDA
 4                                     Priya Kaul DM

                                                    4  \
 0  Lecturer: Sejal Chopra Course: CSL302 Batch: 0...
 1                          REVATHY SUNDARARAJAN AM
 2                          REVATHY SUNDARARAJAN AM
 3                              Deepali Kayande DLDA
 4                          REVATHY SUNDARARAJAN AM

                                                    5  \
 0  Lecturer: Deepali Kayande Course: CSL301 Batch...
 1                              Deepali Kayande DLDA
 2  Lecturer: Sejal Chopra Course: CSL302 Batch: 1...
 3                                 Sejal Chopra ECCF
 4                              Deepali Kayande DLDA

                                                    6 weekdays
 0  Lecturer: Deepali Kayande Course: CSL301 Batch...      Mon
 1                                 Sejal Chopra ECCF       Tue
 2  Lecturer: Sejal Chopra Course: CSL302 Batch: 1...      Wed
 3                                               Free     Thur
 4                                Ali Imran Mirza DS       Fri  ,
                                                    0  \
 0                               Kalpita Wagaskar AA
 1                               Ditty K Varghese MP
 2  Lecturer: Shafaque Course: CSL502 Batch: 3 \nL...
 3                                     Shainila M CN
 4                               Ditty K Varghese MP

                                                    1  \
 0  Lecturer: Sana Course: CSL501 Batch: 2 \nLectu...
 1  Lecturer: Sana Course: CSL501 Batch: 1 \nLectu...
 2  Lecturer: Shafaque Course: CSL502 Batch: 3 \nL...
 3                                     Shainila M CN
 4                                   Priya Kaul DBMS

                                                    2  \
 0  Lecturer: Sana Course: CSL501 Batch: 2 \nLectu...
 1  Lecturer: Sana Course: CSL501 Batch: 1 \nLectu...
 2                                   Priya Kaul DBMS
 3                              Ditty K Varghese BCE
 4                               Kalpita Wagaskar AA

                                                    3  \
 0                                     Shainila M CN
 1                                               Free
 2                               Kalpita Wagaskar AA
 3  Lecturer: Sana Course: CSL501 Batch: 0 \nLectu...
 4                                    Shainila M TCS

                                                    4  \
 0                               Ditty K Varghese MP
 1                               Ditty K Varghese MP
 2                                    Shainila M TCS
 3  Lecturer: Sana Course: CSL501 Batch: 0 \nLectu...
 4                                   Priya Kaul DBMS

                                                    5  \
 0                                    Shainila M TCS
 1                                     Shainila M CN
 2                                    Shainila M TCS
 3  Lecturer: Dipti Jadhav Course: CSL505 Batch: 2 \n
 4  Lecturer: Sana Course: CSL501 Batch: 3 \nLectu...

                                                    6 weekdays
 0                               Kalpita Wagaskar AA       Mon
 1                              Ditty K Varghese BCE       Tue
 2                                   Priya Kaul DBMS       Wed
 3  Lecturer: Dipti Jadhav Course: CSL505 Batch: 2 \n     Thur
 4  Lecturer: Sana Course: CSL501 Batch: 3 \nLectu...      Fri  ,
                              0  \
 0                         Free
 1    Amiya Kumar Tripathy MCC
 2                         Free
 3  Others Dept Level Elective
 4    Amiya Kumar Tripathy MCC

                                                    1  \
 0                                 Dipti Jadhav DSIP
 1                        Others Inst Level Elective
 2                        Others Dept Level Elective
 3                             Kalpita Wagaskar AISC
 4  Lecturer: Dipti Jadhav Course: CSL701 Batch: 2...

                                                    2  \
 0                                 Dipti Jadhav DSIP
 1                             Kalpita Wagaskar AISC
 2  Lecturer: Dipti Jadhav Course: CSL701 Batch: 0...
 3                                               Free
 4  Lecturer: Dipti Jadhav Course: CSL701 Batch: 2...

                                                    3  \
 0  Lecturer: Dipti Jadhav Course: CSL701 Batch: 3...
 1                                 Dipti Jadhav DSIP
 2  Lecturer: Dipti Jadhav Course: CSL701 Batch: 0...
 3  Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n
 4                                 Dipti Jadhav DSIP

                                                    4  \
 0  Lecturer: Dipti Jadhav Course: CSL701 Batch: 3...
 1                          Amiya Kumar Tripathy MCC
 2                                               Free
 3  Lecturer: Dipti Jadhav Course: CSL701 Batch: 1 \n
 4                                               Free

                                                    5  \
 0                        Others Inst Level Elective
 1                             Kalpita Wagaskar AISC
 2                                               Free
 3  Lecturer: Shafaque Course: CSL703 Batch: 2 \nL...
 4                        Others Inst Level Elective

                                                    6 weekdays
 0                          Amiya Kumar Tripathy MCC       Mon
 1                        Others Dept Level Elective       Tue
 2                        Others Dept Level Elective       Wed
 3  Lecturer: Shafaque Course: CSL703 Batch: 2 \nL...     Thur
 4                             Kalpita Wagaskar AISC       Fri  ]

In [120]:
with ExcelWriter("C:\Prayuj Folders\BE_PROJECT\output.xlsx") as writer:
    for n, df in enumerate(list_dfs):
        df.to_excel(writer,'sheet%s' % n)
    writer.save()

In [121]:
for i in range(len(lecturer_list)):
    print(i, lecturer_list[i].name)

0 REVATHY SUNDARARAJAN
1 Deepali Kayande
2 Priya Kaul
3 Sejal Chopra
4 Ali Imran Mirza
5 Ditty K Varghese
6 Shainila M
7 Amiya Kumar Tripathy
8 Dipti Jadhav
9 Kalpita Wagaskar
10 Others
11 Shafaque
12 Phiroj
13 Sana

In [122]:
lecturer_with_scheduled = {}
for i in range(len(rows)):
    for j in range(len(columns)):
        if target_matrix[i][j] == 1:
            if columns[j]['lecturer'] in lecturer_with_scheduled:
                lecturer_with_scheduled[columns[j]['lecturer']].append({'day': rows[i]['day'], 'hour': rows[i]['hour'], 'room': rows[i]['room'], 'course': columns[j]['course'], 'student_group': columns[j]['student_group']})
            else:
                lecturer_with_scheduled[columns[j]['lecturer']] = [{'day': rows[i]['day'], 'hour': rows[i]['hour'], 'room': rows[i]['room'], 'course': columns[j]['course'], 'student_group': columns[j]['student_group'],}]

In [123]:
lecturer_with_scheduled[0]

[{'day': 1, 'hour': 0, 'room': 0, 'course': 'CSC301', 'student_group': 0},
 {'day': 1, 'hour': 4, 'room': 0, 'course': 'CSC301', 'student_group': 0},
 {'day': 2, 'hour': 4, 'room': 0, 'course': 'CSC301', 'student_group': 0},
 {'day': 4, 'hour': 1, 'room': 0, 'course': 'CSC301', 'student_group': 0},
 {'day': 4, 'hour': 4, 'room': 0, 'course': 'CSC301', 'student_group': 0}]

In [124]:
lecturer_slots = {}
for i in range(no_of_hours):
    for j in range(no_of_days):
        if i in lecturer_slots:
            lecturer_slots[i].append('Free')
        else:
            lecturer_slots[i] = ['Free']

In [125]:
for i in lecturer_with_scheduled[0]:
    print(i)

{'day': 1, 'hour': 0, 'room': 0, 'course': 'CSC301', 'student_group': 0}
{'day': 1, 'hour': 4, 'room': 0, 'course': 'CSC301', 'student_group': 0}
{'day': 2, 'hour': 4, 'room': 0, 'course': 'CSC301', 'student_group': 0}
{'day': 4, 'hour': 1, 'room': 0, 'course': 'CSC301', 'student_group': 0}
{'day': 4, 'hour': 4, 'room': 0, 'course': 'CSC301', 'student_group': 0}

In [126]:
student_group_dictionary[0].name

'SE COMPS'

In [127]:
list_of_dfs = []
for lecturer in lecturer_list:
    lecturer_slots = {}
    for i in range(no_of_hours):
        for j in range(no_of_days):
            if i in lecturer_slots:
                lecturer_slots[i].append('Free')
            else:
                    lecturer_slots[i] = ['Free']
    for i in lecturer_with_scheduled[lecturer.id]:
        lecturer_slots[i['hour']][i['day']] = i['course'] + " " + student_group_dictionary[i['student_group']].name
    lecturer_slots["weekdays"] = weekdays
    df = pd.DataFrame(lecturer_slots)
    df.set_index('weekdays')
    list_of_dfs.append(df)

In [128]:
with ExcelWriter("C:\Prayuj Folders\BE_PROJECT\Teachers.xlsx") as writer:
    for n, df in enumerate(list_of_dfs):
        df.to_excel(writer, lecturer_list[n].name)
    writer.save()

In [29]:
chromosome_to_fitness_dictionary = {}
chromosome_to_target_matrix_dictionary = {}

In [30]:
count = 0
for chromosme in intial_population:
    print(count)
    target_matrix, fitness = fillTargetMatrix(chromosme, columns, hours_for_columns, rows, day_dictionary, hour_dictionary, room_dictionary, lecturer_dictionary, student_group_dictionary, course_dictionary, no_of_days, no_of_hours, total_hours)
    chromosome_to_fitness_dictionary[tuple(chromosme)] = fitness
    chromosome_to_target_matrix_dictionary[tuple(chromosme)] = target_matrix
    count+=1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [31]:
for chromosome in intial_population:
    print(chromosome_to_fitness_dictionary[tuple(chromosome)])

92.7710843373494
93.97590361445783
97.59036144578313
92.7710843373494
93.97590361445783
91.56626506024097
90.96385542168674
92.7710843373494
89.1566265060241
91.56626506024097
92.7710843373494
92.7710843373494
92.7710843373494
92.16867469879519
84.33734939759036
93.37349397590361
96.3855421686747
91.56626506024097
87.95180722891567
90.36144578313252

In [32]:
import pickle

In [33]:
# open a file, where you ant to store the data
file = open('intial_population_chromosome_to_fitness_dictionary', 'wb')

# dump information to that file
pickle.dump(chromosome_to_fitness_dictionary, file)

# close the file
file.close()

In [34]:
# open a file, where you ant to store the data
file = open('intial_population_chromosome_to_target_matrix_dictionary', 'wb')

# dump information to that file
pickle.dump(chromosome_to_target_matrix_dictionary, file)

# close the file
file.close()

In [63]:
file = open("generation8", "rb")
new_population = pickle.load(file)
file.close()

In [64]:
chromosome_to_fitness_dictionary = {}
chromosome_to_target_matrix_dictionary = {}

In [65]:
count = 0
for chromosme in new_population:
    print(count)
    target_matrix, fitness = fillTargetMatrix(chromosme, columns, hours_for_columns, rows, day_dictionary, hour_dictionary, room_dictionary, lecturer_dictionary, student_group_dictionary, course_dictionary, no_of_days, no_of_hours, total_hours)
    chromosome_to_fitness_dictionary[tuple(chromosme)] = fitness
    chromosome_to_target_matrix_dictionary[tuple(chromosme)] = target_matrix
    count+=1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [66]:
for chromosome in new_population:
    print(chromosome_to_fitness_dictionary[tuple(chromosome)])

93.97590361445783
96.98795180722891
93.97590361445783
93.97590361445783
99.39759036144578
89.1566265060241
94.57831325301206
98.79518072289157
93.97590361445783
100.0
90.36144578313252
90.36144578313252
90.36144578313252
93.37349397590361
97.59036144578313
96.3855421686747
96.98795180722891
96.98795180722891
96.3855421686747
92.7710843373494

In [67]:
# open a file, where you ant to store the data
file = open('eigth_generation_chromosome_to_fitness_dictionary', 'wb')

# dump information to that file
pickle.dump(chromosome_to_fitness_dictionary, file)

# close the file
file.close()

# open a file, where you ant to store the data
file = open('eigth_generation_chromosome_to_target_matrix_dictionary', 'wb')

# dump information to that file
pickle.dump(chromosome_to_target_matrix_dictionary, file)

# close the file
file.close()

In [195]:
file = open('eigth_generation_chromosome_to_fitness_dictionary', 'rb')
chromosome_to_fitness_dictionary = pickle.load(file)
file.close()
file = open('eigth_generation_chromosome_to_target_matrix_dictionary', 'rb')
chromosome_to_target_matrix_dictionary = pickle.load(file)
file.close()

In [197]:
maximum = 0
for i in chromosome_to_fitness_dictionary:
    if maximum < chromosome_to_fitness_dictionary[i]:
        maximum = chromosome_to_fitness_dictionary[i]
        maximum_chromosome = i

In [198]:
fitness = chromosome_to_fitness_dictionary[maximum_chromosome]

In [199]:
fitness

100.0

In [200]:
target_matrix = chromosome_to_target_matrix_dictionary[maximum_chromosome]